# GitGuardian Configuration
# This file configures GitGuardian security scanning for the SustainAlign project

# Exclude specific files and directories from scanning
exclude:
  - "README.md"  # Exclude README from credential scanning
  - "docs/**"    # Exclude documentation
  - "html/**"    # Exclude static prototypes
  - "*.md"       # Exclude all markdown files

# Exclude specific patterns (sample credentials)
exclude_patterns:
  - "admin@techcorp.com"
  - "admin123"
  - "director@womenempowerment.org"
  - "women123"
  - "admin@sustainalign.local"

# Ignore specific secret types for development
ignore_secrets:
  - "Sample Account Credentials"
  - "Development Passwords"
  - "Test User Accounts"

# Scan settings
scan_settings:
  # Enable scanning for production secrets
  production_secrets: true
  
  # Disable scanning for development/sample data
  development_secrets: false
  
  # Scan frequency
  scan_frequency: "on_push"
