#!/usr/bin/env python3
"""
Environment Setup Script for IBM WatsonX Orchestrate Sample Project
This script helps users set up their environment variables properly
"""

import os
import sys
from pathlib import Path

def check_environment():
    """Check if required environment variables are set"""
    print("🔍 Checking environment variables...")
    
    api_key = os.getenv('WATSON_API_KEY') or os.getenv('WO_API_KEY')
    instance = os.getenv('WO_INSTANCE') or os.getenv('WATSON_SERVICE_URL')
    
    missing_vars = []
    
    if not api_key:
        missing_vars.append('WATSON_API_KEY or WO_API_KEY')
    
    if not instance:
        missing_vars.append('WO_INSTANCE or WATSON_SERVICE_URL')
    
    if missing_vars:
        print("❌ Missing required environment variables:")
        for var in missing_vars:
            print(f"   - {var}")
        return False
    
    print("✅ All required environment variables are set")
    print(f"   API Key: {api_key[:10]}...")
    print(f"   Instance: {instance}")
    return True

def create_env_file():
    """Create .env file from environment variables"""
    print("📝 Creating .env file...")
    
    api_key = os.getenv('WATSON_API_KEY') or os.getenv('WO_API_KEY')
    instance = os.getenv('WO_INSTANCE') or os.getenv('WATSON_SERVICE_URL')
    
    if not api_key or not instance:
        print("❌ Cannot create .env file - missing required variables")
        return False
    
    env_file = Path(__file__).parent.parent / ".env"
    
    with open(env_file, 'w') as f:
        f.write("# IBM WatsonX Orchestrate Configuration\n")
        f.write("# Generated by setup_environment.py\n\n")
        f.write("WO_DEVELOPER_EDITION_SOURCE=orchestrate\n")
        f.write(f"WO_API_KEY={api_key}\n")
        f.write(f"WO_INSTANCE={instance}\n")
        f.write(f"WATSON_API_KEY={api_key}\n")
        f.write(f"WATSON_SERVICE_URL={instance}\n")
    
    print(f"✅ Created .env file: {env_file}")
    return True

def show_setup_instructions():
    """Show instructions for setting up environment variables"""
    print("\n📋 Environment Setup Instructions")
    print("=" * 50)
    print("To use this project, you need to set the following environment variables:")
    print()
    print("1. Set your API key:")
    print("   export WATSON_API_KEY=your-api-key-here")
    print("   # OR")
    print("   export WO_API_KEY=your-api-key-here")
    print()
    print("2. Set your instance URL:")
    print("   export WO_INSTANCE=https://api.ap-south-1.dl.watson-orchestrate.ibm.com")
    print("   # OR")
    print("   export WATSON_SERVICE_URL=https://api.ap-south-1.dl.watson-orchestrate.ibm.com")
    print()
    print("3. For Windows PowerShell:")
    print("   $env:WATSON_API_KEY=\"your-api-key-here\"")
    print("   $env:WO_INSTANCE=\"https://api.ap-south-1.dl.watson-orchestrate.ibm.com\"")
    print()
    print("4. Or create a .env file in this directory with:")
    print("   WATSON_API_KEY=your-api-key-here")
    print("   WO_INSTANCE=https://api.ap-south-1.dl.watson-orchestrate.ibm.com")
    print()
    print("5. Copy env_example.txt to .env and edit it:")
    print("   cp env_example.txt .env")
    print("   # Then edit .env with your actual credentials")

def main():
    """Main function"""
    print("🚀 IBM WatsonX Orchestrate - Environment Setup")
    print("=" * 50)
    
    if check_environment():
        print("\n✅ Environment is properly configured!")
        if create_env_file():
            print("\n🎉 Setup complete! You can now run the other scripts.")
            print("   Try: python chat.py")
            print("   Or: python simple_setup.py")
        else:
            print("\n⚠️  Environment is set but couldn't create .env file")
    else:
        show_setup_instructions()
        print("\n❌ Please set the required environment variables and run this script again.")

if __name__ == "__main__":
    main()
