export default function useProjectCards() {
  const projects = [
    {
      id: 'card-1',
      theme: 'green',
      status: 'verified',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/44f46ecb32-e45e5602ec89eb08d3c6.png',
      alt: 'children in classroom with solar panels on roof, bright educational environment, sustainable energy',
      title: 'Solar-Powered Learning Centers',
      ngo: { name: 'Green Education Foundation', color: 'green' },
      summary: 'Bringing sustainable electricity to rural schools, impacting 2,500+ students across 15 communities.',
      budgetNeeded: 45000,
      credibility: 98,
      tags: [
        { label: 'Education', color: 'green' },
        { label: 'Clean Energy', color: 'blue' },
      ],
    },
    {
      id: 'card-2',
      theme: 'blue',
      status: 'verified',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/60cab717ca-858f1c83264b0a594a15.png',
      alt: 'clean water well in African village, people collecting water, sustainable infrastructure',
      title: 'Clean Water Access Initiative',
      ngo: { name: 'Water for Life NGO', color: 'blue' },
      summary: 'Installing sustainable water systems in underserved communities, providing clean water to 8,000+ people.',
      budgetNeeded: 67500,
      credibility: 95,
      tags: [
        { label: 'Clean Water', color: 'blue' },
        { label: 'Health', color: 'green' },
      ],
    },
    {
      id: 'card-3',
      theme: 'green',
      status: 'review',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/5dd5fe0bf7-4973f059e2e813107fbc.png',
      alt: 'community garden with vegetables, people farming together, sustainable agriculture',
      title: 'Sustainable Agriculture Program',
      ngo: { name: 'Farm to Future Initiative', color: 'green' },
      summary: 'Teaching organic farming techniques to 500+ families, improving food security and income.',
      budgetNeeded: 28900,
      credibility: 87,
      tags: [
        { label: 'Agriculture', color: 'green' },
        { label: 'Food Security', color: 'yellow' },
      ],
    },
    {
      id: 'card-4',
      theme: 'blue',
      status: 'verified',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/57d4e1cbe3-8ed29a14baa07df071bb.png',
      alt: 'women learning computer skills in technology center, empowerment and education',
      title: "Women's Digital Literacy",
      ngo: { name: 'Empower Her Foundation', color: 'blue' },
      summary: 'Providing technology training to 300+ women, enabling economic independence and digital inclusion.',
      budgetNeeded: 32400,
      credibility: 92,
      tags: [
        { label: 'Gender Equality', color: 'purple' },
        { label: 'Technology', color: 'blue' },
      ],
    },
    {
      id: 'card-5',
      theme: 'green',
      status: 'verified',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/25325458d5-ef0f502706181039a057.png',
      alt: 'forest restoration with people planting trees, environmental conservation, green landscape',
      title: 'Forest Restoration Project',
      ngo: { name: 'Green Earth Alliance', color: 'green' },
      summary: 'Restoring 1,200 hectares of degraded forest, planting 50,000+ trees to combat climate change.',
      budgetNeeded: 89200,
      credibility: 96,
      tags: [
        { label: 'Environment', color: 'green' },
        { label: 'Climate Action', color: 'blue' },
      ],
    },
    {
      id: 'card-6',
      theme: 'blue',
      status: 'review',
      image: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/e283997565-95512ca96f68dcebbca7.png',
      alt: 'mobile health clinic serving rural community, medical care, healthcare access',
      title: 'Mobile Healthcare Units',
      ngo: { name: 'Health Access Network', color: 'blue' },
      summary: 'Bringing essential medical services to remote areas, serving 12,000+ patients annually.',
      budgetNeeded: 156000,
      credibility: 84,
      tags: [
        { label: 'Health', color: 'red' },
        { label: 'Access', color: 'blue' },
      ],
    },
  ]
  return { projects }
}


